### ISSUE TITLE
Subtraction without Spaces Doesn't Subtract

### ISSUE THREAD

**Issue by seanlnge** [SardonyxLang/Sardonyx#1]
For instance, writing 5-5 will output -5 instead of 0. If you put spaces however it will correctly output 0.

**Comment by ghost** [comment]
This is a known issue, and can be fixed by moving the parsing of negatives from the lexer into the parser. I'll get to this later; expect a fix by v0.5.0.

**Comment by ghost** [comment]
reopening to make this more visible

**Comment by ghost** [comment]
nvm, this has been fixed in the latest commit to the dev branch
will make a new patch release once langjam ends - feel free to build locally
